### ISSUE TITLE
ftpd hangs after LIST command

### ISSUE THREAD

**Issue by TomMajor** [toelke/lwip-ftpd#1]
Hello Philipp,

I am trying out your code on a Keil MCBSTM32C Board with STM32F107 chip.
FatFS is running fine, but ftpd seems to hang after LIST command, please see UART log. Total Commander (ftp client) seems to wait forever after this LIST command.

Could you please help me narrowing down this issue? I have good microcontroller experience but no experience with ftp protocoll.

Don't know how to contact you otherwise than creating this issue.

Thanks,

---

lwIP 1.4.1 test starting
Trying to mount
Drive mounted
----A 01.01.2011 12:00       610 TEST
   1 File(s),       610 bytes total
   0 Dir(s), 3952599040 bytes free
   FAT type = FAT32

Link on
eth init
response: 220 lwIP FTP Server ready.
query: USER userresponse: 331 User name okay, need password.
query: PASS userresponse: 230 User logged in, proceed.
query: SYSTresponse: 214 UNIX system type.
query: FEATresponse: 502 Command not implemented.
query: HELP SITEresponse: 502 Command not implemented.
query: PWDresponse: 257 "/" is current directory.
query: TYPE AGot TYPE -A-response: 502 Command not implemented.
query: PORT 192,168,1,33,237,124response: 200 Command okay.
query: LISTresponse: 150 File status okay; about to open data connection.

**Comment by toelke** [comment]
Hi Tom,

I would guess this comes from exhausted heap memory or exhausted TCP PCBs.

Could you check those?

Cheers,
Philipp

**Comment by TomMajor** [comment]
Hi Philipp,

thanks for the quick reply. From your name, are you by any chance German 
and could we communicate German?

This is my first start with lwIP and porting and everything is much more 
complicated than I thought, although I found an old ST application note 
with code for lwIP 1.3.1. which I adapted for my board (without an OS 
first).

So my knowldege of lwIP is very limited, how would I check heap memory 
or TCP PCB in the debugger?

This first test on the MCBSTM32C did run ok and this was the project I 
wanted to try ftp on.

In the meantime, I tried to merge this into an existing uCOS-III project 
(which is the final goal) but now I get a hardfault everytime I try to 
access the web server. If I cannot fix this, this will be a show stopper 
for lwIP (I hope not).

Thanks,
Tom

-- Beantwortete Nachricht --

**Comment by toelke** [comment]
Hi Tom,

yes, actually I am from Germany but I would like to keep public communication in English as others might benefit from it.

To check for heap memory, in vfs.c I _should_ check the return value of every malloc and return some sensible value. It is possible ftpd.c relies on some return value being non-NULL.

You could try increasing heap size if that changes anything.
If you want to check how much heap is free, you would need to look into the implementation details of your runtime.
You could also single-step from cmd_list() on and check for NULL pointers being used.

How many TCP pcbs have you configured in lwip? ftp needs one listening pcb and one non-listening. If you have a webserver, it will need further pcbs.

Another thing you could look into: As in ftp the server connects back to the client, sometimes a personal firewall on the client machine can hinder a complete ftp connection.

I will probably not have time in the next four weeks to build necessary error-checking code into this module. I would gladly accept a pull request though...

I hope I can help you  to get this working.

Cheers,
Philipp

**Comment by toelke** [comment]
I will close this now as I do not see how it helps to have it open; I am not sure if your problem is a error in the ftp-code or your port.
