### ISSUE TITLE
Memory leak after client quits session

### ISSUE THREAD

**Issue by m-seker** [toelke/lwip-ftpd#12]
Hi Philipp,

If the client issues a QUIT command, ftpd replies with 221 and waits for the ftpd_msgsent callback to release the allocated resources with the help of ftpd_msgclose. However, following check never lets the code to reach the ftpd_msgclose function :

https://github.com/toelke/lwip-ftpd/blob/master/ftpd.c#L1203

`	if (pcb->state > ESTABLISHED)
		return ERR_OK;
`

pcb->state is always CLOSE_WAIT at this point in case of QUIT command.

Is this check really necessary ? Can we remove it to solve the problem ?

**Comment by toelke** [comment]
Hi,

first of all, thanks for going through the code so thoroughly!

I can only speculate why the original author included the line.
Of course, the call to send_msgdata in line 1211 should be guarded so that it is only tried on at least half-open tcp-connections...

Cheers,
Philipp

**Comment by m-seker** [comment]
Hi,

The code is very clear and easy to follow. It's a joy to try to make it error free.

Maybe we can move that check just above the `send_msgdata(pcb, fsm);` line and below the close snippet ?

**Comment by toelke** [comment]
Yes, that seems sensible.
