### ISSUE TITLE
len wrapped rcv_wnd

### ISSUE THREAD

**Issue by Markmuco** [toelke/lwip-ftpd#22]
Lwip 2.0.3 running on STM32F4 HAL version V1.24.1

The FTP server runs great. However sometimes when FTP send a file from pc to STM using total commander:
message: Assertion "tcp_recved: len wrapped rcv_wnd"

It is because rcv_wnd overflowed This value leads to TCP_MSS default 536 and increasing makes no difference.

Rebooting the STM is the only solution.

**Comment by toelke** [comment]
I am sorry if I do not understand you correctly, but are you sure this is an error in the ftp-server? Do other TCP connections work without that problem?
