### ISSUE TITLE
malloc size of pointer rather than size of struct

### ISSUE THREAD

**Issue by dbinette** [toelke/lwip-ftpd#24]
in  file vfs.c, 
function  vfs_opendir

i'm pretty sure that 
` vfs_dir_t* dir = malloc(sizeof *dir);`
should be
`vfs_dir_t* dir = malloc(sizeof dir);`

**Comment by toelke** [comment]
Hey,

exactly -- we have a pointer (`vfs_dir_t *dir`) and want the size of what it is pointing to. Hence the `sizeof *dir`.

```
me@home ~/tmp$ cat test.c
#include <stdio.h>

int main(unsigned int argc, char **argv) {
  unsigned char *c;
  printf("sizeof *c: %d\n", sizeof *c);
  printf("sizeof c: %d\n", sizeof c);
}
me@home ~/tmp$ gcc -o test test.c
me@home ~/tmp$ ./test
sizeof *c: 1
sizeof c: 8
```

As you can see, `sizeof *c` returns the size of the "structure" and `sizeof c` returns the size of the pointer.

Thank you for your efforts. I appreciate that you took the time to look for problems!

**Comment by dbinette** [comment]
correct, and thanks,  this script illustrates it clearly
 #include <stdio.h>
#include <stdlib.h>

typedef struct el {
char m[234];
} el_t;

int main(unsigned int argc, char **argv)
{
	el_t *c = malloc(sizeof(*c));
	printf("sizeof *c: %d\n", sizeof (*c));
	printf("sizeof c: %d\n", sizeof (c));
	
	el_t *p = malloc(sizeof(el_t));
	printf("sizeof *p: %d\n", sizeof (*p));
	printf("sizeof p: %d\n", sizeof (p));
}

C:\tmp>gcc -o test test.c

C:\tmp>test
sizeof *c: 234
sizeof c: 8
sizeof *p: 234
sizeof p: 8
