### ISSUE TITLE
missing call to f_closedir()  

### ISSUE THREAD

**Issue by dbinette** [toelke/lwip-ftpd#25]
in vfs.c, fuction vfs_closedir  the memory for the directory object is freed but not closed
```
void vfs_closedir(vfs_dir_t* dir)
{ if (dir) 
  {  f_closedir(dir);   // <== need to add this
    free(dir);
  }
}

```

**Comment by toelke** [comment]
Looking at the documentation (http://elm-chan.org/fsw/ff/doc/closedir.html) this is only necessary when `FF_FS_LOCK` is enabled. Of course we should add it here for compatibility.

Can you do the change and pull-request it?
