### ISSUE TITLE
Does not work with FileZilla on windows

### ISSUE THREAD

**Issue by netcu** [toelke/lwip-ftpd#29]
FTP works with linux tools but not with FileZilla on Windows - can you fix this if it is a bug? file transfer does not work. Listing is OK.

**Comment by toelke** [comment]
In #2 somebody needed to build in support for `TYPE I`. In #6, somebody used FZ and "just" had performance issues.

I will take a look at some point, personal life is high-priority right now 👶.

**Comment by toelke** [comment]
I can see filezilla failing when it sends the `TYPE A` command, which is to be expected as only `TYPE I` is supported.

**Comment by toelke** [comment]
With filezilla set to transfer all files as binary (Settings->FTP Transfer), I can successfully upload and download file from lwip-ftpd.

Can you check if that works for you?
