### ISSUE TITLE
Trouble getting ftpd to run

### ISSUE THREAD

**Issue by nikigraus** [toelke/lwip-ftpd#5]
Hello

I am trying to get ftpd running, but after 2 days of debugging, I am stuck. It gets pretty far, but when the file list is being sent, something stucks. It happens with different clients (also the windows built-in).
I have attached a wireshark log and the output of the firmware.
If you have a little time to look at it, I would be very glad.

Thanks and regards,
Daniel

[ftp_MasterMACS.pcapng.txt](https://github.com/toelke/lwip-ftpd/files/134249/ftp_MasterMACS.pcapng.txt)

[log.txt](https://github.com/toelke/lwip-ftpd/files/134248/log.txt)

**Comment by toelke** [comment]
I have never used the passive mode...
As far as I can see you have a complete and correct FTP-Transaction listing all files in /. It gets closed in packets 90-93.
Strangely, the ftp-server only sends the "226 Closing data connection" only after the client closes the control connection in packet 420.

Is the rest of you lwip working? Which port are you using? Are the *_tmr called regularily?

**Comment by nikigraus** [comment]
```
You name it! 5min ago, I also found out
  that the ftpd_msgpoll routine is not called. It is because I use
  an operating system (SYS/BIOS), I think. From where do I have to
  call the _tmr functions?

  Thanks, and regards,
  Daniel


  I have never used the passive mode...
    As far as I can see you have a complete and correct
    FTP-Transaction listing all files in /. It gets closed in
    packets 90-93.
    Strangely, the ftp-server only sends the "226 Closing data
    connection" only after the client closes the control connection
    in packet 420.
  Is the rest of you lwip working? Which port are you using? Are
    the *_tmr called regularily?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by toelke** [comment]
Please read [1] and [2]. Calling "sys_check_timeouts" should suffice.
The mailing list https://lists.nongnu.org/mailman/listinfo/lwip-users will gladly help you with this and other problems in getting the stack to work.

[1] http://lwip.wikia.com/wiki/LwIP_with_or_without_an_operating_system
[2] http://lwip.wikia.com/wiki/LwIP_Platform_Developers_Manual

**Comment by nikigraus** [comment]
I found the problem
It was the define for MEMP_NUM_SYS_TIMEOUT, it was one too little. Therefore there was a failure in memp_malloc(MEMP_SYS_TIMEOUT), so the timers did not run. In turn, also the poll function of ftpd was not called.
Thanks for your help!
Daniel

**Comment by toelke** [comment]
I am glad you found the error. Good luck with your device!
