### ISSUE TITLE
vfs_close deletes guard_for_the_whole_fs

### ISSUE THREAD

**Issue by m-seker** [toelke/lwip-ftpd#9]
Hi Philipp, 

Am I missing something or the following line deletes a global object which is not allocated on heap in case `guard_for_the_whole_fs` is passed as parameter  :

https://github.com/toelke/lwip-ftpd/blob/master/vfs.c#L74

It seems like call to `free` should also be placed inside if block in the following snippet :

```
void vfs_close(vfs_t* vfs) {
	if (vfs != &guard_for_the_whole_fs) {
		/* Close a file */
		f_close(vfs);
	}
	free(vfs);
}

```

**Comment by toelke** [comment]
You are absolutely correct; I wonder why I haven't seen a crash from that...

Thanks!

**Comment by m-seker** [comment]
As far as I can observe, it is never called in happy path scenario since the following check does not allow code to reach the `ftpd_msgclose(pcb, fsm);` call :

`if (pcb->state > ESTABLISHED)
    return ERR_OK;
`

https://github.com/toelke/lwip-ftpd/blob/master/ftpd.c#L1204

And it leaks all related data structures since the cleanup code is not called at all.
